/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        secondary: "#5e5e5e",
        primary: "#000000",
        error: "#ba1a1a",
        background: "#f9f9f9",
        surface: "#f9f9f9",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "on-background": "#1b1b1b",
        "on-surface": "#1b1b1b",
        "secondary-container": "#e3e2e2",
        "on-secondary-container": "#646464",
        "on-secondary-fixed": "#1b1c1c",
        "on-secondary-fixed-variant": "#464747",
        "primary-container": "#1b1b1b",
        "on-primary-container": "#848484",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "surface-variant": "#e2e2e2",
        "on-surface-variant": "#4c4546",
        outline: "#7e7576",
        "outline-variant": "#cfc4c5",
        "surface-dim": "#dadada",
        "surface-bright": "#f9f9f9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f3",
        "surface-container": "#eeeeee",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "inverse-surface": "#303030",
        "inverse-on-surface": "#f1f1f1",
        "inverse-primary": "#c6c6c6",
        "surface-tint": "#5e5e5e",
        "primary-fixed": "#e2e2e2",
        "on-primary-fixed": "#1b1b1b",
        "primary-fixed-dim": "#c6c6c6",
        "on-primary-fixed-variant": "#474747",
        "secondary-fixed": "#e3e2e2",
        "on-secondary-fixed": "#1b1b1b",
        "secondary-fixed-dim": "#c7c6c6",
        tertiary: "#000000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#1b1b1b",
        "on-tertiary-container": "#848484",
        "tertiary-fixed": "#e2e2e2",
        "on-tertiary-fixed": "#1b1b1b",
        "tertiary-fixed-dim": "#c6c6c6",
        "on-tertiary-fixed-variant": "#474747",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "1rem",
        "2xl": "4rem",
        container: {
          DEFAULT: "1200px",
          max: "1200px",
        },
      },
      fontFamily: {
        inter: ["Inter"],
        "body-md": ["Inter"],
        h1: ["Inter"],
        display: ["Inter"],
        h2: ["Inter"],
        "body-sm": ["Inter"],
        "label-caps": ["Inter"],
        h3: ["Inter"],
        button: ["Inter"],
        "body-lg": ["Inter"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        h1: [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        display: [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        h2: ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": [
          "12px",
          { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "700" },
        ],
        h3: ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        button: ["15px", { lineHeight: "1", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
